home:
    path: /home
    controller: App\Controller\HomeController::index

user.logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

user.login:
    path: /login
    controller: App\Controller\SecurityController::login

admin.user.create.choice:
    path: /admin/create/choice
    controller: App\Controller\SecurityController::createChoice

admin.home:
    path: /admin/home
    controller: App\Controller\AdminController::index

admin.create.company:
    path: /admin/create/company
    controller: App\Controller\SecurityController::createCompany



admin.zone.create:
    path: /admin/zone/create
    controller: App\Controller\AdminController::createZone

admin.category.create:
    path: /admin/category/create
    controller: App\Controller\AdminController::addCategory

admin.create.donator:
    path: /admin/create/donator
    controller: App\Controller\SecurityController::createCompany


admin.zones.show:
    path: /admin/zons/show
    controller: App\Controller\AdminController::showZones


admin.categories.show:
    path: /admin/categories/show
    controller: App\Controller\AdminController::showCategories


admin.zone.edit:
    path: /admin/zone/edit/{id}
    controller: App\Controller\AdminController::editZone
    methods: GET|POST
    requirements:
        id: '\d+'

admin.category.edit:
    path: /admin/category/edit/{id}
    controller: App\Controller\AdminController::editCategory
    methods: GET|POST
    requirements:
        id: '\d+'

admin.zone.remove:
    path: /admin/zone/remove/{id}
    controller: App\Controller\Admin\AdminController::removeZone
    methods: DELETE
    requirements:
        id : '\d+'

admin.category.remove:
    path: /admin/category/remove/{id}
    controller: App\Controller\Admin\AdminController::removeCategory
    methods: DELETE
    requirements:
        id : '\d+'

admin.companies.show:
    path: /admin/companies
    controller: App\Controller\AdminController::showCompanies